### ISSUE TITLE
Library Understanding problem

### ISSUE THREAD

**Issue by ronitsrma16** [JRodrigoTech/Ultrasonic-HC-SR04#15]
In the Library file there is written like 
#ifdef ARDUINO>=100
 #include<Arduino.h>
Arduino should greater than from what, I didn't get it?

**Comment by JRodrigoTech** [comment]
Because at the time of its composition, there were incompatibilities between older versions, this code is compatible from version 1.0 onwards.

https://stackoverflow.com/questions/30927908/what-is-the-constant-arduino-for-it-used-to-be-22-but-is-now-100
